expertisesolutions/efl

build.bat
configure.bat

Everytime you call `vcvars64.bat`, it adds Visual Studio variables into `%path%`, eventually leading into `input line too long` error in CMD.
This patch:
- Fixes the `input line too long` issue by just running `vcvars64.bat` if it never ran in current shell session;
- Breaks meson flags into multiple line when showing them (so flag debugging gets _very_ easier).
**OBS:** Please, **rebase+merge** when **both** have reviewed and no errors were encountered.

windows: Prevent path from stacking in every configure/build call.

---

src/lib/evil/unposix/sys/time.c
src/lib/evil/unposix/sys/time.h

Windows:sys/time.h: Correct sys/time.h errors
Summary:
The way sys/time.h was added it was not being compiled in the right way.
PR#16 makes possible to compile unposix/sys, so it was possible to
detect some errors.
The errors were about fault includes.
Now there should be no compile errors at sys/time.h.
Depends on PR#16
Test Plan:
- comment -Wno-missing-variable-declarations at meson.build;
- added -k0 to NINJAFLAGS at build.bat;
- there should not be any errors/warnings about sys/types.h.

Windows:sys/time.h: Correct sys/time.h errors

---

src/lib/evil/unposix/sys/time.h
src/lib/evil/unposix/sys/types.h

It does so by:
- including definitions that Windows already has;
- `typedef` the ones that Windows doesn't have, following `sys/types.h`
manual guidelines;
- `pid_t` is a process id, so on this implementation is
`typedef` as an `DWORD`, the type returned by `GetCurrentProcessId`
function, and thus it is an `unsigned long`. `sys\types.h` manual
establishes that it should be a `signed int` and when changed, it
should not be larger than a `long`;
Depends on PR#16
Test Plan:
- comment `-Wno-missing-variable-declarations` at `meson.build`;
- added `-k0` to `NINJAFLAGS` at `build.bat`;
- there should not be any errors/warnings about sys/types.h.

Windows:sys/types.h: Should add every needed non pthread_* type

---

build.bat

I.e. enables us to just build with `build -k0` instead of editing `build.bat`.

windows: Pass flags to build.bat straight-forwardly

---

src/lib/evil/unposix/sys/time.h

Summary:
Remove the following linking error:
```
[18/1920] Linking target src/lib/evil/unposix/sys/evil_unposix_sys-1.dll.
FAILED: src/lib/evil/unposix/sys/evil_unposix_sys-1.dll
lld-link @src/lib/evil/unposix/sys/evil_unposix_sys-1.dll.rsp
lld-link: error: undefined symbol: localtime_s
>>> referenced by src/lib/evil/unposix/sys/f1142d4@@evil_unposix_sys@sha/time.c.obj:(l
ocaltime_r)
```
`localtime_t` is from `ucrt/time.h`. `#include <time.h>` was not picking
`UCRT` implementation of `time.h`, now it is changed to `#include
<../ucrt/time.h>`, forcing `UCRT`'s implementation.
If at some point `time.h` (`time.h` not `sys/time.h`) is add to
`unposix` this should be changed to `#include <../time.h>` as there
shoud be a `#include_next <time.h>`.
Test Plan:
- added -k0 to NINJAFLAGS at …

Windows:sys/time.h: Remove linking error at localtime_s

---

meson.build

As implicit-function-declaration is a really important warning for who is
reviewing/creating PR's I suggest to disable
`Wno-implicit-function-declaration` at meson build. The ones who need
the warning disabled can do it themselves.

windows: Enable implicit-function-declaration error.

---

.gitignore
configure.bat
header_checks/meson.build
meson.build
meson_options.txt
src/generic/evas/meson.build
src/lib/eina/meson.build
src/lib/emile/meson.build
src/lib/eo/meson.build
src/lib/evas/meson.build
src/lib/evil/meson.build
src/lib/evil/pcre/regex.h
src/lib/evil/unposix/meson.build
src/lib/evil/unposix/stdlib.h
src/lib/evil/unposix/sys/meson.build
src/lib/evil/unposix/sys/time.c
src/lib/evil/unposix/unistd.h
subprojects/pcre.wrap
subprojects/zlib.wrap

Title says it all.
This way we don't have to deal with compiling zlib nor pcre separately, and it is built using `clang-cl` itself, in a manner meson expects. No need for `{ZLIB,REGEX_LIB,REGEX_INCLUDE}_DIR` env-vars.
Next step: do the same with OpenSSL.

windows: Transform zlib and pcre into wrap dependencies

---

header_checks/meson.build
meson.build
meson_options.txt
src/bindings/cxx/meson.build
src/bindings/meson.build
src/generic/evas/meson.build
src/generic/evas/xcf/meson.build
src/lib/ecore/meson.build
src/lib/eet/meson.build
src/lib/efl/meson.build
src/lib/eina/meson.build
src/lib/elementary/meson.build
src/lib/elua/meson.build
src/lib/emile/meson.build
src/lib/eo/meson.build
src/lib/evas/meson.build
src/tests/elua/meson.build

Bug: Compile `native-windows` on Linux
Summary:
========
This PR makes `devs/expertise/native-windows` compile on linux.
lua was a little problematic:
luajit is a default option to bindings in `master` but at
`devs/expertise/native-windows` it was changed to lua, This PR brings
luajit back as a default option, but make a Windows build always use
lua - semantically equal to what happened at
`devs/expertise/native-windows`
Ref Issue #38
Linux Test plan:
================
- `meson` configured with `-Dbindigns=cxx,mono`;
- `ninja` should return every warning that `master` does, nothing else;
- `meson test -C <build dir>` should pass in everything that `master`
does;
Windows Test plan:
==================
- Run `configure.bat` normally;
- Run `build.bat` it should yield the same erros/warnigs …

Compile `devs/expertise/native-windows on Linux

---

src/lib/eina/eina_debug.c
src/lib/eina/eina_debug_timer.c
src/lib/eina/eina_inline_thread_posix.x

The last merge introduced this warnings:
```
[17/4260] Compiling C object 'src/lib/eina/803ee99@@eina@sha/eina_debug_timer.c.o'.
../src/lib/eina/eina_debug_timer.c: In function ‘_monitor’:
../src/lib/eina/eina_debug_timer.c:97:35: warning: extra tokens at end of #ifdef directive
97 | # ifdef EINA_HAVE_PTHREAD_SETNAME || EINA_HAVE_WIN32_THREAD_SETNAME
|                                   ^~
../src/lib/eina/eina_debug_timer.c: In function ‘eina_debug_timer_add’:
../src/lib/eina/eina_debug_timer.c:178:72: warning: passing argument 3 of ‘eina_thread_create’ makes integer from pointer without a cast [-Wint-conversion]
178 |         int err = eina_thread_create(&_thread, EINA_THREAD_BACKGROUND, NULL,(Eina_Thread_Cb)_monitor, NULL);
| …
```

Bug: Remove warnings introduced by last merge

---

src/lib/evil/unposix/meson.build

`libgen.h` and `string.h` no longer exists.

Removing deleted headers

---

src/lib/eina/eina_error.c

`strerror_s` is the windows alternative of `strerror_r` used by EFL.
`strerror_s` never return the error code with the message as
`strerror_r` does, because of that, while comparing the first 14
characters of `Unknown error ` to the message from unknown code 4096
(`Unknown error`) they were accusing being different - in UNIX this
works because the message returned is `Unknown error 4096`.
So comparing only the first 13 characters does the trick.
Depends on #64
Test Plan:
----------
- Apply #64;
- Let every other test case from `eina_suite.c` commented;
- The test should pass;

Eina: Resolve bad comparison while using windows strerror_s

---

src/lib/eina/eina_rbtree.c

Some places at `eina_rbtree.c` were using `_Eina_Iterator_Rbtree_List`
`dir` (an enum bit-field) as an array index, causing a wrong
sign-extension to `-1` that yields a `segfault`.
Test Plan:
----------
- Let every other test case from `eina_suite.c` commented;
- The test should pass;

Fixed problematic sign-extension of enum used as bit-fields at eina_rbtree

---

src/lib/evil/evil_mman.c

Clearly a typo, but this fix will make the test `eina_test_safepointer_reusable`  of `eina_test_safepointer.c` to pass on windows.

Evil: Fixing conversion from size_t to high-low dwords for _WIN64.

---

src/lib/eina/eina_inline_thread_win32.x

Windows threads are "uncancelable" so those functions don't make any sense.
Some functions were called by its eina_thread (public) version so now
the return some kind of error/`EINA_FALSE`.
Before this, it was stopping at `eina_thread_create` ->  `_eina_internal_call`
-> `eina_thread_cancellable_set` L179;
Now it goes a little further but still stops at `eina_thread_create` ->
`_eina_internal_call`; more specificaly it stops inside L74.

Remove cancel functions from windows threads

---

src/tests/eina/eina_test_value.c

This and #66 fix the `eina_test_value` test case on Windows.

Adapt test values converted from [u]int64 to [u]long to avoid overflows 

---

src/tests/eina/eina_test_error.c

Previous it expected "Cannot allocate memory" but windows yields
"Not enough space").
Test Plan:
----------
- Let every other test case from `eina_suite.c` commented;
- The next error will not be related to this;

Change windows expected error message at an ENOMEM error

---

src/lib/eina/eina_vpath.c

Due to this missing brackets, the function returns 0 when it in fact executed the 'if' with success.
This is the cause behind `eina_test_vpath` test failing on windows.

Eina: Missing brackets at eina_vpath()

---

src/lib/eina/meson.build

@cauebs pointed he was having problems with `InitializeSynchronizationBarrier` not being found in `synchapi.h`, which should be false since it's in Windows' C stdlib implementation ([see code here](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.16299.0/um/synchapi.h#L161)).
Checking `<builddir>/meson-logs/meson-log.txt`, the following could be found:
```
Compiler stderr:
In file included from C:\Users\Tiz\source\repos\efl\build\meson-private\tmpvyu6_kne\testfile.c:2:
In file included from C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\synchapi.h:18:
In file included from C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared\minwindef.h:182:
C:\Program Files (x86)\Windows …
```

windows: Fix header symbol check for synchapi.h

---

.github/workflows/windows.yml

Our 'EFL on Windows' Action is failing because the path for meson depends of the installed version of Python, this PR uses the output of `python --version` to get the right path for meson.

Actions: fix meson path

---

src/lib/evil/evil_locale.c

In the Windows platform, setlocale is defined as an alias to
evil_setlocale, causing an infinite recursive call when category is
different from LC_MESSAGE.
We undef setlocale in the implementation file, which will fall back to
the c runtime function.

evil_locale.c: Fix infinite recursion call to evil_setlocale

---

src/lib/eina/meson.build

This reverts commit aaedabebaa6a4f40270c3731af48a843563dc8ea.
The commit broke the EFL build.

Revert "windows: Fix header symbol check for synchapi.h"

---

src/lib/eina/eina_inline_thread_win32.x
src/tests/eina/eina_test_file.c

This has two fixes: a "use after free" bug fix in the Win32 implementation of eina_thread; and the valid test file for `eina_test_file_thread` test case. See individual commits for details.

Fix eina_test_file_thread

---

subprojects/check.wrap

While we don't merge the windows lock fix in the main libcheck, let's
use our fork to keep going with efl port.

[temporary] Use a custom version of libcheck

---

header_checks/meson.build

Accidentally, when check was set to come from the wrap-dependency, we did that only in Windows, but when the system is not  Windows it would be a plain "declare_dependency".
This fixes it by using the [`dependency` kwarg `fallback`](https://mesonbuild.com/Dependencies.html#building-dependencies-as-subprojects), which will:
1. Try to find `check` dependency in system;
2. If not found, it'll search for a subproject `check` and get the `check_dep` variable declared on it.

build: Use check subproject as fallback

---

src/lib/eina/eina_inline_thread_win32.x
src/lib/eina/eina_thread_win32.h

`GetCurrentThread` API returns a pseudo-handle that identifies the current
thread. It returns the same value independent of the calling thread.
This affects thread indentifier comparison as comparing two identifiers
obtained from `eina_thread_self` may compare equal although they are
from different thread.
The correct way to compare thread identifiers in Windows are with values
returned from `GetCurrentThreadId` and `GetThreadId`.

windows: fix eina_thread_equal

---

src/lib/ecore_win32/Ecore_Win32.h
src/lib/ecore_win32/ecore_win32.c
src/lib/ecore_win32/ecore_win32_clipboard.c
src/lib/ecore_win32/ecore_win32_cursor.c
src/lib/ecore_win32/ecore_win32_dnd.c
src/lib/ecore_win32/ecore_win32_event.c
src/lib/ecore_win32/ecore_win32_monitor.c
src/lib/ecore_win32/ecore_win32_window.c
src/lib/ecore_win32/meson.build

Use `ECORE_WIN32_API` instead of `EAPI` and comment `Ecore.h` and `Ecore_input.h`

Use ECORE_WIN32_API instead of EAPI

---

src/lib/eina/eina_inline_thread_posix.x
src/lib/eina/eina_inline_thread_win32.x
src/lib/eina/eina_log.c
src/lib/eina/eina_thread.c
src/lib/eina/eina_thread.h
src/lib/eina/eina_thread_posix.h
src/lib/eina/eina_thread_win32.h
src/lib/eina/meson.build

eina_self_thread returns the type Eina_Thread, which is not guaranteed
to return a type comparable with the == operator or convertable to a
integral type.
This commits introduces the eina_thread_self_id API, which returns a
thread identifier compatible to an integral type.

eina: Implement the eina_thread_self_id API

---

meson.build

Ignores some other more warnings + ignore them for C, C++ and Obj-C.

windows: Ignore additional warnings + for all langs

---

src/lib/eo/eo.c

[By comparing ](https://github.com/expertisesolutions/efl/compare/devs/felipealmeida/eolian-test...devs/cauebs/eo-build) we can see that the original code was:
```
if ((self != _efl_object_main_thread) &&	
(self != klass->construction_thread))	
```
So the desired behavior would be:
```
if (!eina_thread_equal(self, _efl_object_main_thread) &&
!eina_thread_equal(self, klass->construction_thread))
```

add missing "!" to thread inequality

---

src/tests/eina/eina_test_file.c

errno is documented to only contains a valid value for mkstemp if the
function fails.

eina_test_file.c: Do not check errno on success

---

src/tests/eina/eina_test_file.c

errno only holds a valid value if the function returns an error.

eina_test_file.c: Fix eina_test_file_mktemp test case

---

meson.build

Nugget variable was being set on every builds, causing an error at linux
build while configuring the build, now it successfully configures
build.

Linux Build: Make Nugget variable only on windows build

---

src/lib/eina/eina_debug_timer.c
src/lib/eina/eina_pipe.h
src/lib/eina/meson.build
src/lib/evil/evil_unistd.h

As pipe functions were defined at `evil` they were not available to any
other library. Now they are defined at `eina`.
You can have a look at tests with Travis-CI at my [fork](https://github.com/Coquinho/efl/runs/735172415).
Depends on #104

Linux Build: pipe function were not available at a linux build

---

src/lib/eina/eina_log.c

A typo was yielding a linking error.

Linux Build: Correct a typo

---

src/lib/eina/eina_inline_lock_posix.x

`eina_lock_take_try` and `eina_spinlock_take_try` were not defined for
use at `eina_inline_lock_posix.x` causing some implicity declaration of
those.

Linux Build: Resolve implicity declaration at `eina_inline_lock_posix.x`

---

src/lib/eina/eina_main.c

`eina_lock_take` was reciving an aditional `NULL` argumment causing an too many arguments error:
```
../src/lib/eina/eina_main.c:322:4: error: too many arguments to function 'eina_lock_take'
322 |    eina_lock_take(&_eina_tracking_lock, NULL);
|    ^~~~~~~~~~~~~~
In file included from ../src/lib/eina/eina_main.c:43:
../src/lib/eina/eina_lock.h:169:27: note: declared here
169 | EINA_API Eina_Lock_Result eina_lock_take(Eina_Lock *mutex);
|                           ^~~~~~~~~~~~~~
```
~Depends on #110~

Remove unnecessary additional argument

---

src/tests/efl_check.h

As there is no variable array length with `msvc` it was changed to use
`malloc`, but was not correctly changed as nav is a char array.
We can see at `a5a587510e7` that the original definition was:
```
char *nav = (char *)malloc(sizeof(char) * (argc + 3));
```
Which is not equivalent to our current implementation.

Resolve wrong variable array length conversion

---

src/lib/eina/eina_thread_posix.h

There was a typo at `eina_thread_posix.h` `Eina_ThreadId` definition.

OSX Build: Resolve typo of type Eina_ThreadId

---

meson.build

Lua was disabled, causing a meson error at an OSX build.

Reenable Lua

---

src/lib/eina/eina_inline_lock_win32.x
src/tests/eina/eina_test_lock.c

We implement the `clock_gettime` for Windows and set eina error when the condition variable wait times out.

windows: Fix tests cases in eina_test_lock.c

---

src/lib/eina/eina_inline_lock_posix.x

OSX barrier definition may use some lock functions that weren't defined
at this point of compilation, which caused
`-Wimplicit-function-declaration` error.

OSX Build: Resolve implicit-function-declaration error at barrier definition

---

src/lib/eina/eina_inline_lock_win32.x
src/lib/eina/eina_tls_win32.c
src/lib/eina/meson.build

The implementation makes use of the DLL_THREAD/PROCESS_DETACH to call
delete_cb when the thread exits.

windows: Implement delete callback funcionality for tls

---

src/lib/eina/eina_log.c

To achieve this compiling error you need #103

Resolve eina_thread_self_id() typo

---

src/lib/eina/eina_main.c

As spotted by @cauebs, `_eina_tracking_lock` isn't initialized. It seems
that while modifying every `pthread` call to an `eina` call we made a
mistake of changing a `pthread_mutex_init` to an `eina_lock_take`
instead of an `eina_lock_init`, we can see this while comparing
[native-windows](https://github.com/expertisesolutions/efl/blob/devs/expertise/native-windows/src/lib/eina/eina_main.c#L322)
`eina_main.c` to
[master's](https://github.com/Enlightenment/efl/blob/master/src/lib/eina/eina_main.c#L319).

Initialize _eina_tracking_lock

---

src/lib/eina/eina_inline_thread_posix.x

The current definition is causing an error at OSX build, as it doesn't have `pthread_set_name_np`.

Reverse eina_thread_name_set definition

---

src/lib/eina/eina_inline_lock_win32.x

As discussed in #112, this aims to decrease the amount of architecture
dependent functions on code.
Aiming to remove architecture dependent
`EnterCriticalSection`/`LeaveCriticalSection` used with
`_eina_tracking_lock` and instead using
`eina_lock_take`/`eina_lock_release` archteture independent functions

Only use {Enter/Leave}CriticalSection in eina_lock_{take,release} while dealing with _eina_tracking_lock

---

src/lib/ecore/meson.build

The errors were related to:
- Lua was disabled: by just re-enabling it could go further;
- `master` removed the `systemd` option from `ecore`;

Make #89 compilation process achieve the same point of native-windows on Linux

---

src/lib/eina/Eina.h

`eina_pipe` wasn't in `Eina.h` so it was inaccessible for other libraries,
which caused `-Wimplicit-function-declaration` at `ecore_anim.c`.
No by including `Eina.h` it should be enabled.

Add eina_pipe to Eina.h

---

src/tests/efl_check.h

Those comments were added to test the rebase branch, but know they are causing
errors at Linux build.

Remove unnecessary comments on efl_check.h

---

src/lib/eina/eina_inline_lock_posix.x
src/lib/eina/eina_lock.c

Remove barrier new/free declarations, as they happen next to its
definition.
Remove double definitions of OSX spinlock functions.

OSX build: Remove double definition functions

---

src/lib/evil/meson.build

While compiling efl-one, evil variables weren't available.

Work around in evil for efl-one

---

src/tests/efl_check.h

Malloc wasn't being casted, which yielded:
```
../src/tests/eo_cxx/../efl_check.h: In function 'int _efl_test_option_disp(int, char**, const Efl_Test_Case*)':
../src/tests/eo_cxx/../efl_check.h:139:32: error: invalid conversion from 'void*' to 'char**' [-fpermissive]
139 |             char **nav = malloc(sizeof(char*) * (argc + 3));
|                          ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                                |
|                                void*
```

Convert malloc

---

src/lib/eina/eina_file_common.h
src/lib/eina/eina_file_win32.c

On Windows, the file map offset must be a multiple of the system allocation granularity.
We handle the alignment requirement internally. We round down the given offset to the next
aligned value. We then map the aligned offset plus the offset difference plus the map length.
We adjust the returned pointer value to the original offset and store the original pointer inside
the file map structure for use by the unmap function.

windows: fix eina_file_map_new

---

src/lib/eina/eina_inline_lock_win32.x

was transformed **struct Eina_Barrier** from: src/lib/eina/eina_inline_lock_win32.x, into a simple **typedef Eina_Barrier**.
the following functions of the same file have also been modified:
- _eina_barrier_new();
- _eina_barrier_free();
- _eina_barrier_wait.

replacing struct Eina_Barrier with typedef Eina_Barrier

---

meson.build
src/lib/evil/evil_unistd.c
src/tests/evil/evil_suite.c
src/tests/evil/evil_test_unistd.c
src/tests/evil/meson.build

Also reenables evil tests and implements a test case for `ftruncate`.
I noticed that `evil_test_dlfcn` is failing and I'll try to fix it in a subsequent PR.

windows: Implement ftruncate

---

meson.build

While compiling `ecore` it was possible to notice that:
- `src/bin/efl` depends on `ecore_con`;
- `src/generic/evas` depends on `evas`;
- `src/edje_external` and `data` depends on `edje`;
So this PR adds some guards for them.

Add dependency guards

---

src/lib/eina/meson.build

`eina_inline_lock_posix.x`, `eina_inline_lock_win32.x` and `eina_pipe.h`
weren't available as `eina` `public_sub_headers` at `meson.build` making
then unavailable when instaling our build.

Add files to eina public_headers

---

.travis.yml

- Remove notification;
- Only enable `option-disable` build (OSX, MinGW, Wayland and default
builds have been disabled as they don't work for now);
This build compile with these [meson options](https://github.com/expertisesolutions/efl/blob/devs/expertise/native-windows/.ci/ci-configure.sh#L24..#L33):
```
-Daudio=false -Davahi=false -Dx11=false -Dphysics=false -Deeze=false
-Dopengl=none -Deina-magic-debug=false -Dbuild-examples=false
-Dbuild-tests=false  -Dcrypto=gnutls -Dglib=false -Dgstreamer=false
-Dsystemd=false -Dpulseaudio=false  -Dnetwork-backend=connman -Dxinput2=false
-Dtslib=false
-Devas-loaders-disabler=gst,pdf,ps,raw,svg,xcf,bmp,dds,eet,generic,gif,ico,jp2k,json,pmaps,psd,tga,tgv,tiff,wbmp,webp,xpm
-Decore-imf-loaders-disabler=xim,ibus,scim  -Dfribidi=false -Dfontconfig=false …
```

Configure Travis-CI to work on expertise/efl

---

src/lib/eio/meson.build

`-DEIO_BUILD` was surrounded by ´\` instead of `''`.

Eio: Correctly use simple quotes on eio build definition

---

src/lib/edje/edje_edit_eo.h

This should resolve the current CI error.
It needs #200 and #201 to see the error, You can see it at the build log given at #201.
This [branch](https://github.com/expertisesolutions/efl/tree/devs/coquinho/edje_api_weak) has #200, #201 and this one so you can see a new [log](https://travis-ci.com/github/expertisesolutions/efl/builds/173753227).
The error shown *should* be addressed by #180

Resolve typo `EDJE_WEAK_API` to `EDJE_API_WEAK`

---

src/lib/evil/evil_unistd.h

Typo in _fileno, missing stdio include

---

src/lib/ecore_avahi/Ecore_Avahi.h
src/lib/ecore_avahi/ecore_avahi.c
src/lib/ecore_avahi/ecore_avahi_api.h
src/lib/ecore_avahi/meson.build

[ecore_avahi] Use ECORE_AVAHI_API instead of EAPI

---

src/lib/ecore_drm2/Ecore_Drm2.h
src/lib/ecore_drm2/ecore_drm2.c
src/lib/ecore_drm2/ecore_drm2_api.h
src/lib/ecore_drm2/ecore_drm2_device.c
src/lib/ecore_drm2/ecore_drm2_fb.c
src/lib/ecore_drm2/ecore_drm2_outputs.c
src/lib/ecore_drm2/ecore_drm2_plane.c
src/lib/ecore_drm2/meson.build

[ecore_drm2] Use ECORE_DRM2_API instead of EAPI

---

src/lib/ecore_drm/Ecore_Drm.h
src/lib/ecore_drm/ecore_drm.c
src/lib/ecore_drm/ecore_drm_api.h
src/lib/ecore_drm/ecore_drm_device.c
src/lib/ecore_drm/ecore_drm_evdev.c
src/lib/ecore_drm/ecore_drm_fb.c
src/lib/ecore_drm/ecore_drm_inputs.c
src/lib/ecore_drm/ecore_drm_launcher.c
src/lib/ecore_drm/ecore_drm_output.c
src/lib/ecore_drm/ecore_drm_sprites.c
src/lib/ecore_drm/ecore_drm_tty.c
src/lib/ecore_drm/meson.build

[ecore_drm] Use ECORE_DRM_API instead of EAPI

---

src/lib/ethumb/Ethumb.h
src/lib/ethumb/Ethumb_Plugin.h
src/lib/ethumb/ethumb.c
src/lib/ethumb/ethumb_api.h
src/lib/ethumb/ethumb_private.h
src/lib/ethumb/meson.build

[ethumb] Use ETHUMB_API instead of EAPI

---

src/lib/embryo/Embryo.h
src/lib/embryo/embryo_amx.c
src/lib/embryo/embryo_api.h
src/lib/embryo/embryo_main.c
src/lib/embryo/embryo_private.h
src/lib/embryo/meson.build

[embryo] Use EMBRYO_API instead of EAPI

---

src/lib/elua/Elua.h
src/lib/elua/cache.c
src/lib/elua/elua.c
src/lib/elua/elua_api.h
src/lib/elua/meson.build

[elua] Use ELUA_API instead of EAPI

---

src/lib/elput/Elput.h
src/lib/elput/elput.c
src/lib/elput/elput_api.h
src/lib/elput/elput_input.c
src/lib/elput/elput_manager.c
src/lib/elput/elput_touch.c
src/lib/elput/meson.build

[elput] Use ELPUT_API instead of EAPI

---

src/lib/eeze/Eeze.h
src/lib/eeze/Eeze_Disk.h
src/lib/eeze/Eeze_Net.h
src/lib/eeze/Eeze_Sensor.h
src/lib/eeze/eeze_api.h
src/lib/eeze/eeze_disk.c
src/lib/eeze/eeze_disk_dummy.c
src/lib/eeze/eeze_disk_libmount.c
src/lib/eeze/eeze_disk_libmount_new.c
src/lib/eeze/eeze_disk_libmount_old.c
src/lib/eeze/eeze_disk_mount.c
src/lib/eeze/eeze_disk_udev.c
src/lib/eeze/eeze_main.c
src/lib/eeze/eeze_sensor.c
src/lib/eeze/eeze_sensor_private.h
src/lib/eeze/eeze_udev_find.c
src/lib/eeze/eeze_udev_syspath.c
src/lib/eeze/eeze_udev_walk.c
src/lib/eeze/eeze_udev_watch.c
src/lib/eeze/meson.build

[eeze] Use EEZE_API instead of EAPI

---

src/lib/emile/Emile.h
src/lib/emile/emile_api.h
src/lib/emile/emile_base64.c
src/lib/emile/emile_base64.h
src/lib/emile/emile_cipher.c
src/lib/emile/emile_cipher.h
src/lib/emile/emile_cipher_gnutls.c
src/lib/emile/emile_cipher_openssl.c
src/lib/emile/emile_compress.c
src/lib/emile/emile_compress.h
src/lib/emile/emile_image.c
src/lib/emile/emile_image.h
src/lib/emile/emile_main.c
src/lib/emile/meson.build

[emile] Use EMILE_API instead of EAPI

---

src/lib/ecore_win32/Ecore_Win32.h
src/lib/ecore_win32/ecore_win32.c
src/lib/ecore_win32/ecore_win32_api.h
src/lib/ecore_win32/ecore_win32_clipboard.c
src/lib/ecore_win32/ecore_win32_cursor.c
src/lib/ecore_win32/ecore_win32_dnd.c
src/lib/ecore_win32/ecore_win32_monitor.c
src/lib/ecore_win32/ecore_win32_window.c
src/lib/ecore_win32/meson.build

[ecore_win32] Use ECORE_WIN32_API instead of EAPI

---

src/lib/efreet/Efreet.h
src/lib/efreet/Efreet_Mime.h
src/lib/efreet/Efreet_Trash.h
src/lib/efreet/efreet.c
src/lib/efreet/efreet_api.h
src/lib/efreet/efreet_base.c
src/lib/efreet/efreet_base.h
src/lib/efreet/efreet_cache.c
src/lib/efreet/efreet_cache_private.h
src/lib/efreet/efreet_desktop.c
src/lib/efreet/efreet_desktop.h
src/lib/efreet/efreet_desktop_command.c
src/lib/efreet/efreet_icon.c
src/lib/efreet/efreet_icon.h
src/lib/efreet/efreet_ini.c
src/lib/efreet/efreet_ini.h
src/lib/efreet/efreet_menu.c
src/lib/efreet/efreet_menu.h
src/lib/efreet/efreet_mime.c
src/lib/efreet/efreet_private.h
src/lib/efreet/efreet_trash.c
src/lib/efreet/efreet_uri.c
src/lib/efreet/efreet_uri.h
src/lib/efreet/efreet_utils.c
src/lib/efreet/efreet_utils.h
src/lib/efreet/meson.build

[efreet] Use EFREET_API instead of EAPI

---

src/lib/eet/Eet.h
src/lib/eet/eet_api.h
src/lib/eet/eet_cipher.c
src/lib/eet/eet_connection.c
src/lib/eet/eet_data.c
src/lib/eet/eet_dictionary.c
src/lib/eet/eet_image.c
src/lib/eet/eet_lib.c
src/lib/eet/eet_node.c
src/lib/eet/meson.build

[eet] Use EET_API instead of EAPI

---

src/modules/elementary/web/none/elm_web_none_eo.h

There was stil a EWAPI which [yields](https://travis-ci.com/github/expertisesolutions/efl/builds/174202249#L2290):
```
In file included from ../src/modules/elementary/web/none/elm_web_none.c:17:
../src/modules/elementary/web/none/elm_web_none_eo.h:22:6: error: expected ';' before 'const'
22 | EWAPI const Efl_Class *elm_web_none_class_get(void);
|      ^~~~~~
|      ;
```

[modules] Bug: Remove remaining EWAPI

---

src/lib/ecore_ipc/Ecore_Ipc.h
src/lib/ecore_ipc/ecore_ipc.c
src/lib/ecore_ipc/ecore_ipc_api.h
src/lib/ecore_ipc/meson.build

[ecore_ipc] Use ECORE_IPC_API instead of EAPI

---

src/lib/ecore_input_evas/Ecore_Input_Evas.h
src/lib/ecore_input_evas/ecore_input_evas.c
src/lib/ecore_input_evas/ecore_input_evas_api.h
src/lib/ecore_input_evas/meson.build

[ecore_input_evas] Use ECORE_INPUT_EVAS_API instead of EAPI

---

src/lib/ecore_imf/Ecore_IMF.h
src/lib/ecore_imf/ecore_imf.c
src/lib/ecore_imf/ecore_imf_api.h
src/lib/ecore_imf/ecore_imf_context.c
src/lib/ecore_imf/ecore_imf_module.c
src/lib/ecore_imf/meson.build

[ecore_imf] Use ECORE_IMF_API instead of EAPI

---

src/lib/ecore_file/Ecore_File.h
src/lib/ecore_file/ecore_file.c
src/lib/ecore_file/ecore_file_api.h
src/lib/ecore_file/ecore_file_download.c
src/lib/ecore_file/ecore_file_monitor.c
src/lib/ecore_file/ecore_file_path.c
src/lib/ecore_file/meson.build

[ecore_file] Use ECORE_FILE_API instead of EAPI

---

src/lib/ecore_fb/Ecore_Fb.h
src/lib/ecore_fb/ecore_fb.c
src/lib/ecore_fb/ecore_fb_api.h
src/lib/ecore_fb/ecore_fb_li.c
src/lib/ecore_fb/ecore_fb_private.h
src/lib/ecore_fb/ecore_fb_ts.c
src/lib/ecore_fb/ecore_fb_vt.c
src/lib/ecore_fb/meson.build

[ecore_fb] Use ECORE_FB_API instead of EAPI

---

src/lib/ecore_evas/Ecore_Evas.h
src/lib/ecore_evas/ecore_evas.c
src/lib/ecore_evas/ecore_evas_api.h
src/lib/ecore_evas/ecore_evas_buffer.c
src/lib/ecore_evas/ecore_evas_deprecated.c
src/lib/ecore_evas/ecore_evas_ews.c
src/lib/ecore_evas/ecore_evas_extn.c
src/lib/ecore_evas/ecore_evas_private.h
src/lib/ecore_evas/ecore_evas_util.c
src/lib/ecore_evas/meson.build

[ECORE_EVAS] Use ECORE_EVAS_API instead of EAPI

---

src/lib/ecore_cocoa/Ecore_Cocoa.h
src/lib/ecore_cocoa/ecore_cocoa_api.h
src/lib/ecore_cocoa/meson.build

[ecore_cocoa] Use ECORE_COCOA_API instead of EAPI

---

src/lib/ecore_buffer/Ecore_Buffer.h
src/lib/ecore_buffer/Ecore_Buffer_Queue.h
src/lib/ecore_buffer/ecore_buffer.c
src/lib/ecore_buffer/ecore_buffer_api.h
src/lib/ecore_buffer/ecore_buffer_consumer.c
src/lib/ecore_buffer/ecore_buffer_provider.c
src/lib/ecore_buffer/ecore_buffer_queue_main.c
src/lib/ecore_buffer/meson.build

[ecore_buffer] Use ECORE_BUFFER_API instead of EAPI

---

src/lib/ecore_input/Ecore_Input.h
src/lib/ecore_input/ecore_input.c
src/lib/ecore_input/ecore_input_api.h
src/lib/ecore_input/ecore_input_compose.c
src/lib/ecore_input/ecore_input_joystick.c
src/lib/ecore_input/meson.build

[ecore_input] Use ECORE_INPUT_API instead of EAPI

---

src/lib/ecore/ecore_main.c

I think this functions should be intern and therefore don't need to be exported. If it is not the case, its declaration in .h is missing the `ECORE_EAPI` symbol.

[Ecore] Fixing a dll export

---

src/lib/eina/eina_inline_lock_win32.x

The callback is only supposed to be called on thread exit.

windows: Fix tls free callback

---

src/lib/evas/common/evas_image_scalecache.c
src/lib/evil/evil_unistd.c
src/lib/evil/evil_unistd.h

* now `usleep()` is implemented in evil (PR #192), then we don't need to keep the `Sleep()` specifically for windows, and then we don't need to include `windows.h` here.
* stdint.h include removed because it was only needed because of uint64_t.
* from [IEEE](https://pubs.opengroup.org/onlinepubs/007904975/basedefs/sys/types.h.html): _The type useconds_t shall be an unsigned integer type capable of storing values at least in the range [0, 1000000]. The type suseconds_t shall be a signed integer type capable of storing values at least in the range [-1, 1000000]._, -> then it is here defined as `unsigned int`.

Fixing undefined useconds_t

---

configure.bat

This will probably make some new breaking changes, e.g. `libjpeg` not being found anymore :) But it is for good.

build: Use PKG_CONFIG_LIBDIR to ignore pkg-config from strawberry-perl

---

src/lib/efl_canvas_wl/Efl_Canvas_Wl.h
src/lib/efl_canvas_wl/efl_canvas_wl_api.h
src/lib/efl_canvas_wl/meson.build

`lib_api.h`;
8. Add `LIB_api.h` to public headers;
9. If files are generated here, add `-e` flag to `eolian_gen` with
`LIB_API` as argument (It didn't happen until now);

[efl_canvas_wl] Use EFL_CANVAS_WL_API instead of EAPI

---

src/lib/ephysics/EPhysics.h
src/lib/ephysics/ephysics_api.h
src/lib/ephysics/ephysics_body.cpp
src/lib/ephysics/ephysics_camera.cpp
src/lib/ephysics/ephysics_constraints.cpp
src/lib/ephysics/ephysics_main.cpp
src/lib/ephysics/ephysics_quaternion.cpp
src/lib/ephysics/ephysics_shape.cpp
src/lib/ephysics/ephysics_world.cpp
src/lib/ephysics/meson.build

[ephysics] Use EPHYSICS_API instead of EAPI

---

src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_common.c

As specified at `__declspec(dllexport)`
[doc](https://docs.microsoft.com/pt-br/cpp/build/exporting-from-a-dll-using-declspec-dllexport?view=vs-2017),
`__declspec(dllexport)` should be to the left of any other
calling-convention keyword.

[module] Bug: Move `extern` keyword to the right of API definitions

---

src/lib/ethumb_client/Ethumb_Client.h
src/lib/ethumb_client/ethumb_client.c
src/lib/ethumb_client/ethumb_client_api.h
src/lib/ethumb_client/meson.build

`lib_api.h`;
8. Add `LIB_api.h` to public headers;
9. If files are generated here, add `-e` flag to `eolian_gen` with
`LIB_API` as argument (It didn't happen until some other PR);

[ethumb_client] Use ETHUMB_CLIENT_API instead of EAPI

---

src/lib/ecore_wayland/Ecore_Wayland.h
src/lib/ecore_wayland/ecore_wayland_api.h
src/lib/ecore_wayland/ecore_wl.c
src/lib/ecore_wayland/ecore_wl_dnd.c
src/lib/ecore_wayland/ecore_wl_input.c
src/lib/ecore_wayland/ecore_wl_output.c
src/lib/ecore_wayland/ecore_wl_subsurf.c
src/lib/ecore_wayland/ecore_wl_window.c
src/lib/ecore_wayland/meson.build

[ecore_wayland] Use ECORE_WAYLAND_API instead of EAPI

---

src/lib/ecore_sdl/Ecore_Sdl.h
src/lib/ecore_sdl/ecore_sdl.c
src/lib/ecore_sdl/ecore_sdl_api.h
src/lib/ecore_sdl/meson.build

[ecore_sdl] Use ECORE_SDL_API instead of EAPI

---

.gitignore
header_checks/meson.build
src/lib/evas/meson.build
subprojects/freetype2.wrap
win32-deps/meson.build

Currently freetype2 is get using Nuget, but as freetype2 do exists as a meson wrap, we could be using it to built from sources instead of getting binaries with Nuget.

Getting freetype2 from meson wrap

---

meson.build
src/bindings/cxx/meson.build
src/lib/efreet/meson.build

Since MSVC builds don't know how to deal with Pkg-config, this commit changes them into a [disabler-object](https://mesonbuild.com/Reference-manual.html#disabler-object), which makes all operations using the variable `pkgconfig` to be disabled (i.e. ignored).

build: Disable pkgconfig operations for MSVC (Fixes #150)

---

meson.build
native-file-windows.txt
src/lib/emile/emile_cipher_openssl.c
src/lib/evil/evil_stat.h
win32-deps/meson.build

Turns out that emile doesn't need ecore, so I redone the work of PR #120 here, sending it directly to windows-native.
Test:
```
23/23 emile-suite               OK             0.10s
```

[Emile] [Redone] Building with tests

---

src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_api.h
src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_common.c
src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_egl.c
src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_shm.c

Before that Travis-CI [yields](https://travis-ci.com/github/expertisesolutions/efl/jobs/358111661#L3640):
```
../src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_common.c:9:8: error: expected ';' before 'extern'
9 | EMODAPI extern Eina_List *_evas_canvas_image_data_unset(Evas *eo_e);
|        ^~~~~~~
|        ;
../src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_common.c:10:8: error: expected ';' before 'extern'
10 | EMODAPI extern void _evas_canvas_image_data_regenerate(Eina_List *list);
|        ^~~~~~~
|        ;
```

[modules] EMODAPI wans't available for everything in evas_ecore_wayland

---

src/lib/eina/meson.build

\#209 removed lock `.x` files from public headers causing
[Travis](https://travis-ci.com/github/expertisesolutions/efl/builds/174619415) to yield:
```
/usr/local/include/eina-1/eina/eina_lock.h:103:11: fatal error: eina_inline_lock_posix.x: No such file or directory
103 | # include "eina_inline_lock_posix.x"
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

[Linux] Bug: Add lock `.x` files to eina public headers

---

src/bin/eolian/headers.c
src/bin/eolian/main.c
src/bin/eolian/sources.c
src/bin/eolian/types.c

This makes most tests in the `eolian_generation` test case pass.

eolian_gen: Don't fall back to EAPI if symbol isn't specified with -e

---

src/examples/elementary/meson.build
src/examples/elementary/win_example.c

For some reason, `ecore_x` wasn't being set at `elementary` or at least while compiling `win_example.c`, so this PR explicitly adds `ecore_x`.

Linux build: Explicitly add ecore_x dependency to elementary examples

---

src/tests/eo/suite/eo_test_general.c

EFL_CALLBACKS_ARRAY_DEFINE reorders the callbacks according to
efl_callbacks_cmp. efl_callbacks_cmp compares the address of the desc
field, which depends on the memory layout generated by the linker.
To make the test run deterministically, we define the array of callbacks
manually.

eo_test_general.c: Make eo_signals tests pass on Windows

---

src/tests/eolian/eolian_generation.c

Works around #218 so that eolian_generation tests can be ran on Windows.
Changes helper functions to pass around the filename already with the extension and use `-o type:filename` instead of `-o basename`.

Clean up eolian_generation test to work around #218

---

meson.build

As commented in #138, building eet is straight-forward, but its tests is failing:
```
24/24 eet-suite                 FAIL           12.93s (exit status 1)
```

Building eet

---

.travis.yml
src/bindings/mono/efl_mono/meson.build
src/lib/efl_mono/efl_custom_exports_mono.c
src/lib/efl_mono/efl_mono_accessors.c
src/lib/efl_mono/efl_mono_api.h
src/lib/efl_mono/efl_mono_model_internal.c
src/tests/efl_mono/dummy_test_object.c
src/tests/efl_mono/libefl_mono_native_test.h
src/tests/efl_mono/meson.build

`lib_api.h`;
8. Add `LIB_api.h` to public headers;
9. If files are generated here, add `-e` flag to `eolian_gen` with
`LIB_API` as argument (It didn't happen until now);
This one also worked on efl_mono tests, so `EAPI`/`EWAPI`/`EOAPI` were removed,
where those were defined, now I define …

[efl mono] Define and use EFL_MONO_API

---

src/examples/elementary/toolbar_cxx_example_01.cc

This is the only `EAPI` on `src/example` beside it, there is `EAPI_MAIN` (which is defined by core) so I'm following the pattern that this `EAPI` should be `EAPI_MAIN`.

[WIP] [Bug] An example was using EAPI instead of EAPI_MAIN as all the others

---

meson.build

This PR is redoing #139, but merging to native-windows.
Ector is building and passing tests:
```
25/25 ector-suite               OK             0.11s
```
Note that this PR depends on (#273).

Building Ector

---

src/tests/ecore/ecore_test_ecore.c
src/tests/ecore/ecore_test_ecore_input.c
src/tests/ecore/ecore_test_ecore_thread_eina_thread_queue.c
src/tests/ecore/ecore_test_idle.c
src/tests/ecore/ecore_test_poller.c
src/tests/ecore/efl_app_suite.c
src/tests/ecore/efl_app_test_cml.c
src/tests/ecore/efl_app_test_env.c
src/tests/ecore/efl_app_test_loop.c
src/tests/ecore/efl_app_test_loop_fd.c
src/tests/ecore/efl_app_test_loop_timer.c
src/tests/ecore/efl_app_test_promise.c
src/tests/ecore_con/ecore_con_test_ecore_con_url.c

This is based on
[5d28ab4](https://github.com/expertisesolutions/efl/commit/5d28ab4) but
instead of removing `unistd.h`, this adds guards making it only included
on non-native windows builds.

[ecore] Guard unistd for native windows builds

---

src/lib/efl/efl_api.h
src/lib/efl/meson.build

As `EFL_BUILD` is already a thing, this changes `EFL_BUILD` to
`EFL_LIB_BUILD` removing any chance of wrongly setting it.
Based on [946db](https://github.com/expertisesolutions/efl/commit/946db530a7dc799b841f24311b68a23ebc439497)

[efl] Change efl build definition

---

src/lib/ecore/efl_core_proc_env.c
src/lib/evil/evil_stdlib.h

ref: https://docs.microsoft.com/en-us/cpp/c-runtime-library/environ-wenviron?view=vs-2019

extern char **_environ is already defined by ucrt.

---

src/lib/eina/eina_thread_queue.c
src/tests/ecore/ecore_test_ecore.c
src/tests/ecore/ecore_test_ecore_thread_eina_thread_queue.c
src/tests/ecore/efl_app_test_loop_fd.c

Use `pipe_write`, `pipe_read` and `pipe_close` instead of `write`, `read`, `close`.

[ecore] Use eina_pipe

---

src/lib/ecore_evas/ecore_evas.c
src/lib/ecore_evas/ecore_evas_module.c
src/lib/evas/canvas/efl_canvas_vg_gradient.c
src/lib/evas/canvas/efl_canvas_vg_gradient_linear.c
src/lib/evas/canvas/evas_async_events.c
src/lib/evas/canvas/evas_font_dir.c
src/lib/evas/canvas/evas_image_private.h
src/lib/evas/common/evas_image_load.c
src/lib/evas/common/evas_pipe.c
src/lib/evas/common/evas_pipe.h
src/lib/evas/file/evas_path.c
src/lib/evas/include/evas_common_private.h
src/modules/evas/engines/software_generic/evas_native_dmabuf.c
src/tests/evas/evas_test_image.c

This is based on [805dccea](https://github.com/expertisesolutions/efl/commit/805dccea1434e7bc6bbf1d112b29ba58063475e0) but instead of guarding with `_WIN32` I'm guarding it with `_MSC_VER` as this should already work with `msys`

evas: Add guards to some includes

---

.github/workflows/windows.yml

Motivation: avoid false positives in tests that compare generated files to references from the repo.
Closes #289

Set git core.autocrlf to input in the Windows CI

---

.github/workflows/windows.yml

This shaves off at least a minute from the CI builds :rocket: 
Meson and Ninja are Python applications. Installing through choco probably required downloading a much beefier package, with an embedded CPython build. Installing with pip is the logical way to do it, especially considering we already install Meson this way.

Install ninja through pip on Windows CI

---

configure.bat

Enables running \`configure \<args\>\` (e.g. \`configure -Dlua-interpreter=luajit\`)

build: Enable sending extra args to configure.bat

---

src/generic/evas/meson.build

Based on https://github.com/expertisesolutions/efl/commit/f199fbc671f0827999eccc283734ea9d7b98defe

win32: Fix unistd.h include and incdir

---

configure.bat

These options are setting exactly the default set in `meson_options.txt` and since windows have a very short limited line-length for commands we can save some characters here for future usage.

Removing redundant parameters

---

src/bin/ecore_con/efl_net_proxy_helper.c

This change is needed because `winsock.h/winsock2.h` define a `shutdown` function so we have a naming clash here. 
As we don't have power over `winsock.h/winsock2.h` , our alternative is to change _our_ function name.
Depends on #312 as you can see at `devs/coquinho/clean/evas-fixes` but as ecore_con is not being compiled yet, this doesn't need to be merged after #312;
Based on 2c3143b57eb966797e8df96c7f61d02e858a3dc2

Rename shutdown as proxy_helper_shutdown

---

configure.bat

In `configure.bat`, the user may want to add custom flags to meson calling:
```console
$ configure <extra args to meson>
```
Meanwhile, a "verbose" mode was also available for configure, which would send `-v` flag to the `clang-cl` compiler (making it always output its command line, so there would be no need to check every `.rsp` to see compiler flags).
Previously, verbose output from configure only had effect if `--verbose` was the **first** argument. Not only that, we had a hidden bug on it:
- Since `%MESONFLAGS_EXTRA%` was used (instead of `!MESONFLAGS_EXTRA!`), no flags were sent to meson from `configure` command line (because of how delayed expansion works on Windows);
- By fixing the usage of  `!` instead of `%`, since there was no filter on extra args sent to meson, the `--verbose` …

build: Properly handle --verbose arg

---

src/lib/eet/eet_image.c

Without this, we have some errors about redefining things from jpeg like:
```
In file included from ../src/lib/eet/eet_image.c:12:
In file included from ..\subprojects\jpeg\jpeglib.h:25:
subprojects\jpeg\jconfig.h(11,9): warning: 'HAVE_STDLIB_H' macro redefined [-Wmacro-redefined]
#define HAVE_STDLIB_H
^
.\config.h(116,9): note: previous definition is here
#define HAVE_STDLIB_H 1
^
In file included from ../src/lib/eet/eet_image.c:12:
In file included from ..\subprojects\jpeg\jpeglib.h:25:
subprojects\jpeg\jconfig.h(12,9): warning: 'HAVE_LOCALE_H' macro redefined [-Wmacro-redefined]
#define HAVE_LOCALE_H
^
.\config.h(106,9): note: previous definition is here
#define HAVE_LOCALE_H 1
^
In file included from ../src/lib/eet/eet_image.c:14:
In file included from ..\src\lib\eet/Eet.h:100:
In …
```

win32: eet image inclusion order because of jpeg typedefs

---

src/lib/ecore_evas/ecore_evas_fallback_selection.c

The function available_types do not get ownership of the acceptable_types, and so shouldn't free the stringshares it receives. Doing so causes double free.
Original from https://github.com/expertisesolutions/efl/commit/60c3f1e8a5a8ad2c052c00a4be3bda450d781514

win32: Remove multiple frees for stringshare

---

meson.build

After #159 Ecore will be building fine **without tests**.
However before this PR is ready for review we need to:
To be clear why **without tests**, to enable test to be built we'll need to build:
- ecore_file  
- ecore_con  
- ecore_input  
- ecore_evas  
- ecore_input_evas  
- evas  
- ecore_win32
- ecore_imf  
- _and possibly others..._

[Deps] [Redone] Ecore without tests

---

configure.bat

Stops demanding OPENSSL_DIR environment variable in order to compile, using it only if defined.

build: Use installed openssl when available

---

src/lib/evil/evil_basename.c
src/lib/evil/evil_basename.h
src/lib/evil/evil_dlfcn.h
src/lib/evil/evil_fcntl.h
src/lib/evil/evil_langinfo.h
src/lib/evil/evil_locale.h
src/lib/evil/evil_macro_wrapper.h
src/lib/evil/evil_main.h
src/lib/evil/evil_mman.c
src/lib/evil/evil_mman.h
src/lib/evil/evil_stdio.h
src/lib/evil/evil_stdlib.h
src/lib/evil/evil_string.h
src/lib/evil/evil_strings.c
src/lib/evil/evil_strings.h
src/lib/evil/evil_time.c
src/lib/evil/evil_time.h
src/lib/evil/evil_unistd.h
src/lib/evil/evil_util.h
src/lib/evil/evil_vasprintf.h
src/lib/evil/evil_windows.h

This PR is replacing every `[<\"]evil_*[>\"]` occurrence from `src/lib/evil` to `"evil_private.h"` except from the `src/lib/evil/evil_private.h` itself. 
From https://github.com/expertisesolutions/efl/pull/323#discussion_r457891012:
> You should not include evil_api.h except in evil_private.h. You can think that evil_private.h is "the lib", the others are just "organized parts of it".
> So no one includes evil_{something that is not 'private'}.h, but evil_private.h includes everyone. Meanwhile no evil_* header includes any other evil_* (not even evil_private.h), every other file should include evil_private.h if it wants to use evil.

[Evil] Replacing every evil_*.h include with evil_private.h

---

meson.build

This enables `ecore_con`, `ecore_file`, `ecore_imf`, `ecore_input` and `ecore_win32`.
Note that only `ecore_con` has tests, and it is failing.
Will be a draft, waiting for #294 to be merged.

Enable ecore sublibs

---

src/tests/eina/eina_test_array.c

Just a small fix to [this](https://travis-ci.com/github/expertisesolutions/efl/jobs/361273167#L3571) warning: [result](https://travis-ci.com/github/expertisesolutions/efl/jobs/361715932#L3609).

[Eina test]Removing a warning by fixing a cast

---

src/lib/evil/evil_fcntl.h

UCRT `fcntl.h` already define those as `_<FLAG>` and by defining
`_CRT_DECLARE_NONSTDC_NAMES` it does a `#define _<FLAG> <FLAG>` making
them available the way a POSIX system expects.
This corrects the error of undefined idetifiers on file creation/status
flags such as:
```
../src/tests/ecore/ecore_test_ecore_file.c(262,24): error: use of undeclared identifier 'O_RDWR'
fd = open(src_file, O_RDWR | O_BINARY | O_CREAT, 0700);
^
../src/tests/ecore/ecore_test_ecore_file.c(262,44): error: use of undeclared identifier 'O_CREAT'
fd = open(src_file, O_RDWR | O_BINARY | O_CREAT, 0700);
^
../src/tests/ecore/ecore_test_ecore_file.c(309,24): error: use of undeclared identifier 'O_RDWR'
fd = open(src_file, O_RDWR | O_BINARY | O_CREAT, 0400);
^
../src/tests/ecore/ecore_test_ecore_file.c(309,44): error: …
```

evil: Define file creation flags and file status flags

---

src/examples/ecore/ecore_audio_custom.c
src/examples/ecore/ecore_audio_playback.c
src/examples/ecore/ecore_audio_to_ogg.c
src/examples/ecore/ecore_con_server_http_example.c
src/examples/ecore/ecore_con_url_download_example.c
src/examples/ecore/ecore_evas_basics_example.c
src/examples/ecore/ecore_evas_ews_example.c
src/examples/ecore/ecore_evas_extn_plug_example.c
src/examples/ecore/ecore_evas_extn_socket_example.c
src/examples/ecore/ecore_event_example_02.c
src/examples/ecore/ecore_exe_example.c
src/examples/ecore/ecore_exe_example_child.c
src/examples/ecore/ecore_fd_handler_example.c
src/examples/ecore/ecore_idler_example.c
src/examples/ecore/ecore_job_example.c
src/examples/ecore/ecore_pipe_simple_example.c
src/examples/ecore/ecore_poller_example.c
src/examples/ecore/ecore_thread_example.c
src/examples/ecore/ecore_time_functions_example.c
src/examples/ecore/ecore_timer_example.c
src/examples/eet/eet-data-cipher_decipher.c
src/examples/eet/eet-data-file_descriptor_01.c
src/examples/eet/eet-data-file_descriptor_02.c
src/examples/eet/eet-data-nested.c
src/examples/eet/eet-data-simple.c
src/examples/eina/eina_value_03.c
src/examples/emotion/emotion_generic_example.c

This is a rework of some commits necessary build examples on windows.
based on:
- 2a93955b05f83ab32d26749357fbb849f6c1c561
- f5778429c655e9641b60fb72557449171472927f
- 276d039c35d31df2f2a2adebad6240a373d27356

[win32] [examples] Adding guards to headers for windows compatibility

---

src/lib/eina/eina_inline_lock_win32.x

As `count_init` may be 0, we should not set the maximun count as
`count_init`.
Original: fd8042ad956dd7b36501a222b6bdda4a50b44088

Eina: Max count of semaphore must be greater than 0

---

src/lib/evil/evil_main.c

Without this `ecore-suite`, `efl-app` and `evas-suite` gets timeout:
```
25/29 ecore-suite               TIMEOUT        30.12s
26/29 efl-app                   TIMEOUT        30.14s
...
29/29 evas-suite                TIMEOUT        60.07s
```
As a side effect, this speed up `evil`'s tests thus closing #190.
Based on 8d083963454a9da3045a53315954bd321c75230e

evil: Remove unnecessary delay for evil startup

---

src/lib/elementary/Efl_Ui.h
src/lib/elementary/elm_main.c
src/tests/elementary/suite_helpers.c

`_efl_startup_time` is declared in [Ecore library](https://github.com/expertisesolutions/efl/blob/devs/coquinho/clean/evas-fixes/src/lib/ecore/ecore.c#L47).
It shouldn't be declared in Elementary because it causes mismatches with
importing and exporting of symbol by MSVC's linker.
Original: 06552189d14ff466f93345c87ecdcbf0b7ca526f

elm: Remove declaration from the wrong library

---

header_checks/meson.build
src/lib/evil/evil_time.c
src/lib/evil/evil_time.h

Implemente `evil_localtime_r` using win32 `localtime` function.  If
`HAVE_lOCALTIME_R` is not defined, do it and define `localtime_r` as
`evil_localtime_r`.
Original: 0832953c9eae40851f35b300c25f5a19e35879ef

evil: Implement evil_localtime_r using localtime

---

src/lib/eina/eina_inline_modinfo.x

Always use dllexport for module macros.
originally: 4d74e5e4c8f8e68c5063dc0895755ed06cc64c2c

win32: Module macros are always export

---

.github/workflows/windows.yml

Meson has a flag to show only failed tests' logs (see [other test options section of manual](https://mesonbuild.com/Unit-tests.html#other-test-options), so this will make test loggin a lot less noisy.
But to not loose potential debugging info, the logs are still shown after execution, but in another task.
I also took the chance to rename some steps in order to make them more..."fitting".

ci: Minimize logs noise.

---

src/lib/edje/Edje_Common.h

originally: a0562d5dd72c3d0cb83f8ab6f429707fa37a340e

clang: Fix enumeration signed overflow

---

.ci/ci-configure.sh
meson_options.txt
src/bindings/meson.build
src/lib/elua/meson.build
src/scripts/meson.build

> Elua is now disabled by default. There are some other changes:
> 
> 1) Elua scripts are only installed if Elua is enabled
> 2) Lua bindings are only installed if Elua is enabled
> 3) Elua with interpreter is clearly experimental and will message
Originally: c3a1060b94ae9df82e8406b481e8bd5fe5741df5
This PR conflicts with #342 .

build: disable elua by default, plus nicer detection

---

src/lib/evas/canvas/evas_object_textblock.c

To explain a bit, `Evas_Textblock_Align_Auto` is an enum with four defiined values (0 to 3), which could be correctly represented with 2 bits if enum is unsigned, but if enum is signed, it would need 3 bits instead, than an overflow occur.
To deal with it, here we are forcing `halign_auto` to be an `unsigned int` on windows, inevitably loosing the enum flavor. Other option could be reserving one more bit to `halign_auto`, but I don't know what could be its side-effects.

win32: Fix signed overflow with bitsets and enumerations

---

meson.build

This enables:
- ecore_imf_evas
- ecore_input_evas
- ecore_ipc
And re-enables ecore tests
Depends on #332

Enable every thing we can with evas

---

.github/workflows/windows.yml
src/tests/eolian/data/.gitattributes

We are currently setting `core.autocrlf` to `input` on Windows, to checkout files without converting line endings to CRLF, but that means we expect anyone cloning the repo to do the same or tests will fail.
Now, I'm setting the line ending for the specific files that **need** to use LF.
Credits to @JPTIZ for the finding!

Preserve line endings when checking out eolian_gen reference files

---

src/bin/elementary/meson.build

The Elementary build on windows stops on the following error:
```
ninja: error: build.ninja:10612: multiple rules generate src/bin/elementary/elementary_test.pdb [-w dupbuild=err]
```
There is no need for library elementary_test_lib_name at all, so we are removing it with the upstream commit 338a529af190f0c9c285e932a765f39ae4047a03.
Originally c74e968991c663f23f67118050630b8c4e684670 (from evas-fixes)
Solved with: 338a529af190f0c9c285e932a765f39ae4047a03

win32: fix multiple rules generate for elementary test

---

src/examples/elementary/meson.build

Yeah, we are talking specifically about `phtread` here. `usleep` is already available from `Evil`.
Originally 97d5ddbc2f1fe62c0e3da4cc129cb40ddabb3639

win32: Avoid compiling examples that use platform-specific functions not available in Windows

---

src/lib/efreet/efreet_menu.c
src/lib/efreet/meson.build

Originally:  
- b18901bbb7b48f12d36e9e2a75dbff903062f721
- 0eefd715c48a2f2604fad8551ee8f962b5d0cda7

win32: Don't compile kde legacy and deprecated efreed

---

src/lib/elementary/elm_module_helper.h

`EMODAPI_WEAK` is needed by elementary:
```
..\src\modules\elementary\web\none/elm_web_none_eo.h(22,9): error: unknown type name 'EMODAPI_WEAK'
```

win32: Define EMODAPI_WEAK for Windows

---

meson.build
src/bin/elementary/meson.build
src/bin/elementary/test.c
src/lib/ecore_con/meson.build
src/lib/elementary/Elementary.h
src/lib/elementary/efl_access_object.c
src/lib/elementary/efl_ui_win.c
src/lib/elementary/elm_config.c
src/lib/elementary/elm_main.c
src/lib/elementary/elm_menu.c
src/lib/elementary/meson.build
src/tests/elementary/efl_ui_suite.c
src/tests/elementary/elm_suite.c
src/tests/elementary/meson.build

This makes `eldbus` optional by making it dependent on `dbus` option.
As now it is optional, this:
- removes is from ignored subprojects;
- set `eldbus` option to false for native-windows builds;
- remove it and `atspi` from `elementary` default dependencies and add it when `dbus` option is enabled;
- make related files only compile when `dbus` option is enabled;
- guard related code in `elementary` with `HAVE_ELDBUS`;
Note that `HAVE_<LIB>` is already defined at [meson.build](https://github.com/expertisesolutions/efl/blob/devs/expertise/native-windows/meson.build#L563).
Originals:
- 5202192b0569873093d2441e48b6187b6c98d194
- 2e0c6914f6937b33ac423e6a7c1125a53f364dc2

Make eldbus depended of dbus

---

src/bin/elementary/embed_config.c
src/lib/elementary/meson.build

This PR fixes the following error when trying to build elementary:
```
FAILED: src/lib/elementary/elementary-1.dll.p/elm_config.c.obj
<...>
In file included from ../src/lib/elementary/elm_config.c:1706:
src/lib/elementary\elm_default_config.x(1,1): error: expected identifier or '('
"static const char *embedded_config = \"\""
^
```

elm: Use platform neutral embed_config C program instead of script

---

meson.build

We now have `ecore_con` and `evas` enabled, so we don't need those
checks;
`doxygen` is already guarded by a `doxygen.found()`;
This partialy reverts #136: 3d0c9f7ddd7ca8c07a661e9f3c06e0c88648d4d4

Remove unnecessary guards

---

meson.build

..without `elementary` and `edje` examples
Tests:
```
33/36 efl / edje-suite                FAIL           1.32s (exit status 255 or signal 127 SIGinvalid)
34/36 efl / elementary-suite          FAIL           3.09s (exit status 3221226525 or signal 3221226397 SIGinvalid)
35/36 efl / efl-ui-suite              FAIL           0.74s (exit status 3221226525 or signal 3221226397 SIGinvalid)
36/36 efl / efl_ui_spec-suite         FAIL           0.75s (exit status 3221226525 or signal 3221226397 SIGinvalid)
```
Note that even removing libs from `ignored_subprojects` only `edje` and
`elementary` are enabled by this PR. Those are still not compiled:
```
ecore_audio
ecore_avahi
ecore_buffer
ecore_cocoa
ecore_drm
ecore_drm2
ecore_fb
ecore_sdl
ecore_wayland
ecore_wl2
ecore_x
eeze
efl_canvas_wl
eldbus …
```

Enable elementary+edje

---

src/lib/evil/evil_main.c

Current version checking is done with GetVersion, which is now
deprecated and issues the warning:
```
'GetVersion' is deprecated [-Wdeprecated-declarations]
```
The first approach of this commit was to replace GetVersion call with
the newer (and more reliable) `IsWindowsVistaOrGreater()` from
versionhelpers.h, but nowadays it makes more sense to actually not even
make that check, since it is more than unlinkely to happen that someone
tries to compile/run EFL in Windows XP.
This is a PR from the following phab's Differential Revision: https://phab.enlightenment.org/D12095

evil: Remove OS version check

---

src/lib/eet/eet_cipher.c

In some systems, OpenSSL raises an error about "No Applink" (see ["I've compiled a program under Windows and it crashes: why?" in OpenSSL FAQ](https://www.openssl.org/docs/faq.html#PROG3)). Including only openssl/applink.c didn't work, so the solution was to replace `FILE*` interfaces with OpenSSL's BIO API which also contains file operations.
Notice that this doesn't solve Eet fully, since now that applink works (for this case), there are tests failing.

eet: Fix 'No OPENSSL_Applink' error message.

---

header_checks/meson.build

When fetching `freetype2` and `libjpeg` dependencies, the error message was wrongly stating that it tried only the alternatives (when it actually tried the given library name too). So this patch changes this:
```
Dependency "freetype2" not found. Tried: freetype.
```
To this:
```
Dependency "freetype2" not found. Tried: freetype2, freetype.
```

build: Also include libname into 'Tried: <lib list>'

---

src/bin/edje/edje_codegen.c
src/bin/elementary/elementary_codegen.c
src/examples/edje/meson.build
src/examples/elementary/meson.build

This is needed because Windows platform doesn't have a good way to pass
environment variables to executables through meson, so we pass through a
command-line instead.
As `ecore_evas` and `edje` needs in-tree here they are initialize after
in-tree parameter check.
Original:
- f5b3fd6f3a
- a0208c36b6

win32: Add --in-tree parameter for edje_codegen and elementary_codegen

---

src/bin/edje/edje_cc_out.c

`pending_threads` was being incremented in every iteration making `edje`
wait for inexistent threads.
Now it is only incremented before the thread use.
Original: 3997580d3a78768c9bea3a7ec75b7e036fb887a9

edje: Fix pending_threads calculation and avoid an infinite loop

---

src/lib/evil/evil_fcntl.c

In case a file `length` and `fl->start` are `0` 
`length - fl->start - 1 = -1` which doesn't make sense as a file length

evil: Fix fcntl for F_SETLK and F_SETLKW wrong length calculation

---

src/tests/eet/eet_test_cache.c

This test case had 2 problems one while creating a temporary file and other
while closing it:
About creating the file: `/tmp` doesn't exist in windows and `mkstemp` expects
that all path given already exists (besides the file it will create), causing a
fail:
```
74:    fail_if(-1 == (tmpfd = mkstemp(file)));
```
Here this is solved by using `eina_file_mkstemp` that creates a temporary file
at a temporary directory obtained with `eina_envitonment_tmp` which is an
architecture-independent function.
About closing it: `eet_close` is a postponed close, it doesn't immediately close
files opened as `write and read` nor `write` unless it has non saved changes nor
immediately closes files opened as `read` files. So when arriving at `unlink`
the file may not be closed yet. 
On linux it isn't a …

Eet: Resolve eet_test_cache test case

---

src/tests/eet/eet_test_image.c

Like others `eet` test cases, this test case had 2 problems one while creating a
temporary file and other while closing it:
About creating the file: `/tmp` doesn't exist in windows and `mkstemp` expects
that all path given already exists (besides the file it will create), causing a
fail:
```
../src/tests/eet/eet_test_image.c:93:F:Eet Image:eet_test_image_normal:0: Failure '-1 == (tmpfd = mkstemp(file))' occurred
../src/tests/eet/eet_test_image.c:459:F:Eet Image:eet_test_image_small:0: Failure '-1 == (tmpfd = mkstemp(file))' occurred
```
Here this is solved by using `eina_file_mkstemp` that creates a temporary file
at a temporary directory obtained with `eina_envitonment_tmp` which is an
architecture-independent function.
About closing it: `eet_close` is a postponed close, it doesn't …

Eet: Resolve eet_test_image test case

---

src/lib/ecore_file/ecore_file.c
src/tests/ecore/ecore_test_ecore_file.c

Work toward  #397
Failing initialy with:
```
../src/tests/ecore/ecore_test_ecore_file.c:186:F:Ecore_File:ecore_test_ecore_file_operations:0: Failure 'res != EINA_TRUE' occurred
```
This happens because `UCRT`'s `remove` only works on files, it doesn't
call `rmdir` in case the specified path is a directory
instead of a file like in Linux.
So this patch changes `ecore_file_remove`: now it verifies if the given
path is a directory and if so calls the correct function
(`ecore_file_rmdir`).
Next, there are some file permission related errors, this happens
because Windows only has 2 file permissions:
- `_S_IREAD ==  0o400` which means a read-only file;
- `_S_IWRITE == 0o200` which means a file with write permission;
- `_S_IWRITE | _S_IREAD == 0o600` which is equivalent to `_S_IWRITE`;
Because …

ecore_file: Resolve  ecore_test_ecore_file_operations

---

src/examples/eet/eet-data-cipher_decipher.c
src/examples/eet/eet-data-file_descriptor_01.c
src/examples/eet/eet-data-file_descriptor_02.c
src/examples/eet/eet-data-nested.c
src/examples/eet/eet-data-simple.c
src/tests/eet/eet_test_cache.c
src/tests/eet/eet_test_cipher.c
src/tests/eet/eet_test_file.c
src/tests/eet/eet_test_identity.c
src/tests/eet/eet_test_image.c

As `tmpfile` are being created using `eina_file_mkstemp()`, we can use `eina_file_unlink()` instead of `unlink()`, which closes the handles before unlink (see implementation [here](https://github.com/expertisesolutions/efl/blob/devs/expertise/native-windows/src/lib/eina/eina_file_win32.c#L794https://github.com/expertisesolutions/efl/blob/devs/expertise/native-windows/src/lib/eina/eina_file_win32.c#L794)).
This also removes the need to call `eet_clearcache()` before `unlink()` as the handles are being closed by `eina_file_unlink()`.
This patch is a candidate to solve https://phab.enlightenment.org/T8795.

Use eina_file_unlink() instead of unlink()

---

src/examples/eet/eet-data-cipher_decipher.c

The example `build/src/examples/eet/eet-data-cipher_decipher.exe` was using `mkstemp()` to create temporary files in `/tmp`, which doesn't exist in windows. This patch changes it to use `eina_file_mkstmp()`, which correctly uses the OS temp folder.
Before:
```PowerShell
ERROR: could not create temporary file (/tmp/eet_cipher_example_fS49ra) : File exists
```
After:
```PowerShell
c:\users\coku\joaoantoniocardoso\efl\build\src\examples\eet\eet-data-cipher_decipher.exe (process 4672) exited with code 0.
```

[Eet] [Examples] Fix eet-data-cipher_decipher.exe

---

src/lib/eet/eet_cipher.c
src/tests/eet/eet_suite.c
src/tests/eet/eet_test_identity.c

Before:
```PowerShell
24/35 eet-suite                 TIMEOUT        37.92s
--- command ---
Running suite(s): Eet
95%: Checks: 22, Failures: 1, Errors: 0
../src/tests/eet/eet_test_identity.c:74:F:Eet Identity:eet_test_identity_simple:0: Failure '-1 == (fd = mkstemp(file))' occurred
```
After solving temporary file creation:
```PowerShell
Running suite(s): Eet
OPENSSL_Uplink(00007FF9E25D9D30,08): no OPENSSL_Applink
1/1 eet-suite FAIL           0.97s (exit status 1)
```
After including `openssl/applink.c`:
```PowerShell
Running suite(s): Eet
24/35 eet-suite                 OK             2.69s
```

Eet: Resolve eet_test_identity test case

---

meson.build
src/modules/ecore_evas/meson.build
src/modules/evas/engines/meson.build

Different from the original intention, this doesn't make modules names
work the same in Linux and windows. This workaround the need for a
script for native windows builds but lets other platforms work as they
already do. This only change module names for its final version
(`module`) when on native windows builds. To achieve this, it creates a
`sys_native_windows` variable, which is only true when using `msvc` or
`clang-cl` while in a `windows` host.
Original: 2f3c8295db3e1fa9c62462dbeb6057085e19f87e

Evas: Call evas modules by its final name in native-windows builds

---

meson.build
src/modules/ecore_evas/meson.build
src/modules/evas/engines/meson.build

Reverts expertisesolutions/efl#380
Unfortunatelly it was broken and we forgot to rerun CI to have an up-to-date run before merging.

Revert "Evas: Call evas modules by its final name in native-windows builds"

---

meson.build
src/lib/evas/file/evas_module.c
src/modules/ecore_evas/meson.build
src/modules/evas/engines/meson.build

On native-windows we don't have the `MODULE_ARCH` at the path of
modules, so `evas` we don't need to search there;
Another change at the name is that on native-windows builds we want to
use the final name of modules instead of it intermediary one.
So this changes module names for its final version (`module`) when on
native windows builds. To achieve this, it creates a
`sys_native_windows` variable, which is only true when using `msvc` or
`clang-cl` while in a `windows` host.
Original:
- 2f3c8295db3e1fa9c62462dbeb6057085e19f87e
- 426386578bb6f4e045474dbf1d94a502f29ff18b
Co-authored-by: Felipe Magno de Almeida <felipe@expertise.dev>

Evas: Fix evas modules name in native-windows builds

---

.github/workflows/windows.yml

In order to have better control over dependencies on vcpkg on CI, this PR uses a hash of the current contents of `.github/workflows/windows.yml` as the vcpkg cache key. This means that vcpkg cache will only be invalidated (i.e. vcpkg will be cloned & setuped and then dependencies will be installed one by one) when that file changes (possibly by adding a new dependency).

ci: Make vcpkg cache unique for each workflow change.

---

.github/workflows/windows.yml
header_checks/meson.build

libcurl cannot be used if meson doesn't link it:
```PowerShell
ERR:ecore_con ../src/lib/ecore_con/ecore_con_url_curl.c:255 _c_init()
Cannot find libcurl at runtime!
```

Fix: add libcurl to meson

---

src/examples/eet/eet-file.c

The `example build/src/examples/eet/eet-file.exe` was trying to create temporary files in `/tmp`, which doesn't exist in windows. This patch changes it to use `getenv("TEMP")`, which correctly uses the OS temp folder.

[Eet] [Examples] Fix: eet-file.exe

---

src/lib/elementary/elm_config.c

When there is no `elm_config` it was randomly created with
`eina_file_mkstemp` as `<TEMP DIR>/tmp/elementary_config`, which is a
problem because internally `evil` calls `open` to create the file, but
it cannot create a dir. Thus failing at elm initialization.
This was tested at `examples/elementary/label_example_01.c` that was
failing without running anything of itself.
Now it runs to the end, but failing on almost every other call.

elm: Fix how elm_config was created

---

src/modules/elementary/access_output/meson.build
src/modules/elementary/meson.build
src/modules/elementary/prefs/meson.build
src/modules/elementary/test_entry/meson.build
src/modules/elementary/test_map/meson.build
src/modules/elementary/web/none/meson.build

On Windows, we want to use the final name of modules `module.dll`
instead of its real name like in Linux.
Test Plan
=========
This was tested with `example/elementary/bg_example_0[1,2,3].exe` but it is
expected that with this, there should be no error about failing to load
`prefs_iface` module at elm examples.

 elm: Change module names

---

src/lib/ecore_evas/ecore_evas_module.c
src/lib/elementary/elm_main.c

`elm` was using `/usr/local/[bin, lib, share]` which don't exist on
native-windows, this change it to paths set at `build\config.h`:
- `/usr/local/bin` -> `PACKAGE_BIN_DIR` == `<prefix>/bin`;
- `/usr/local/lib` -> `PACKAGE_LIB_DIR` == `<prefix>/lib`;
- `/usr/local/share` -> `LOCALE_DIR/..` == `<prefix>/share/local/..`;
Note that `<prefix>/share/local/` doesn't exist.
Depends on #415 
Test plan
=========
With this, `example/elementary/bg_example_02.c` should show a image, without
this, the image should not be found.

 elm: Fix path search for app_data

---

src/lib/evas/meson.build

Add cmake_args and use vcpkg module name

win32: Create alternative to find fontconfig from vcpkg

---

src/tests/eolian/eolian_generation.c

- eolian: Call eolian_gen in _eolian_gen_execute_rsp
- eolian: fix test function arguments
- eolian: fix all eolian_gen_execute/files_compare usage in all tests

eolian: Fix failures on eolian_gen tests
