configure.bat

See #6.
No warnings should appear.

Ignore all warnings for now

---

src/lib/evil/meson.build
src/lib/evil/unposix/sys/time.c
src/lib/evil/unposix/sys/time.h

This should add all needed functions/structures from sys/time.h on a Windows fashion.

Add implementation on of sys/time.h

---

src/lib/eina/eina_inline_thread_win32.x

CreateThread was running the new thread before the creator thread received
its pointer, causing `fail_if(!eina_thread_equal(t, thread));` to fail
because the variable `thread` wasn't a pointer to the new thread.
Test Plan:
----------
- Let every other test case from `eina_suite.c` commented;
- The next error will not be related to this;
- This test should run until L112 of `_eina_test_lock_thread` at the
main thread, (here the main thread stops first so I don't know exactly
the new thread stops yet).

windows: Prevent running the thread before finishing its creation

---

src/lib/eina/eina_inline_lock_win32.x
src/lib/eina/meson.build

The only remaining is spinlock, which is currently implemented with a
mutex/CRITICAL_SECTION. This is will be fixed in a follow up commit.

eina_inline_lock_win32.x: Finish implementation of lock primitives

---

src/lib/ecore_win32/Ecore_Win32.h
src/lib/ecore_win32/meson.build
src/lib/ecore_win32/stub_ecore_funcs.c
src/lib/ecore_win32/stub_ecore_funcs.h
src/lib/ecore_win32/stub_ecore_types.h

This PR includes every stub needed to compile this branch

Compile ecore_win32

---

src/lib/eina/eina_inline_lock_posix.x

`_eina_tracking_lock` was been seted as diferents types at `eina_main.c`
and `eina_inline_lock_posix.x` causing:
```
../src/lib/eina/eina_main.c:113:20: error: conflicting types for '_eina_tracking_lock'
113 | EINA_API Eina_Lock _eina_tracking_lock;
|                    ^~~~~~~~~~~~~~~~~~~
In file included from ../src/lib/eina/eina_lock.h:103,
from ../src/lib/eina/eina_main.c:43:
../src/lib/eina/eina_inline_lock_posix.x:155:33: note: previous declaration of '_eina_tracking_lock' was here
155 | EINA_API extern pthread_mutex_t _eina_tracking_lock;
|                                 ^~~~~~~~~~~~~~~~~~~
```
~Depends on #111~

Linux Build: Use Eina_Lock instead of pthread_mutex_t

---

.ci/ci-configure.sh
.ci/ci-make.sh

Master just resolved some errors I got, they were about trying to use `luajit` as a binding, instead of `lua`. So here I bring the 2 commits that happened on `.ci` after our "rebase" with `master`

Update our CI with master

---

configure.bat
meson.build
src/bindings/cxx/meson.build
src/generic/evas/meson.build

Here I enable some Linux functions while maintaining them disabled at
`configure.bat` for windows.

Reenable some Linux functions

---

meson.build
src/bin/eet/eet_main.c
src/lib/eet/eet_cipher.c
src/lib/eet/eet_lib.c
src/tests/eet/eet_test_cache.c
src/tests/eet/eet_test_cipher.c
src/tests/eet/eet_test_file.c
src/tests/eet/eet_test_identity.c
src/tests/eet/eet_test_image.c
src/tests/eet/meson.build

After emile (#120), eet is building straight-forward.

[Deps] eet

---

meson.build
src/bin/eet/eet_main.c
src/lib/eet/eet_cipher.c
src/lib/eet/eet_lib.c
src/tests/ector/suite/meson.build
src/tests/eet/eet_test_cache.c
src/tests/eet/eet_test_cipher.c
src/tests/eet/eet_test_file.c
src/tests/eet/eet_test_identity.c
src/tests/eet/eet_test_image.c
src/tests/eet/meson.build

After eet (#138), ector is building with no effort.

[Deps] Ector

---

src/lib/eo/eo.c
src/lib/eo/eo_ptr_indirection.c

Pulling a couple of commits that are being used in several branches to native-windows

Use eina_thread_equal

---

src/bin/eet/eet_main.c
src/bin/eolian/main.c
src/lib/ecore/ecore.c
src/lib/ecore/ecore_anim.c
src/lib/ecore/ecore_main.c
src/lib/ecore/ecore_main_timechanges.c
src/lib/ecore/ecore_thread.c
src/lib/ecore/ecore_throttle.c
src/lib/ecore/ecore_time.c
src/lib/ecore/efl_appthread.c
src/lib/ecore/efl_loop.c
src/lib/ecore/efl_loop_message.c
src/lib/ecore/efl_loop_message_handler.c
src/lib/ecore/efl_thread.c
src/lib/ecore_input/ecore_input_joystick.c
src/lib/eet/eet_cipher.c
src/lib/eet/eet_lib.c
src/tests/eet/eet_test_cache.c
src/tests/eet/eet_test_cipher.c
src/tests/eet/eet_test_file.c
src/tests/eet/eet_test_identity.c
src/tests/eet/eet_test_image.c

There are several unistd imports left in the sources that needed to be fixed in order to be built on windows.

unistd imports fix

---

src/lib/eina/eina_fnmatch.c
src/lib/eina/eina_fnmatch.h

`EINA_API` macro wasn't being used at eina_fnmatch

Add EINA_API to fnmatch

---

src/lib/eina/eina_types.h

After this, there should be no EAPI or EWAPI at eina.

Eina: Remove remaining EWAPI

---

meson.build
src/tests/evil/evil_test_dlfcn.c
src/tests/evil/meson.build

Reenable evil suite

---

src/modules/ecore_evas/engines/cocoa/ecore_evas_cocoa.c
src/modules/ecore_evas/engines/drm/ecore_evas_drm.c
src/modules/ecore_evas/engines/extn/ecore_evas_extn.c
src/modules/ecore_evas/engines/fb/ecore_evas_fb.c
src/modules/ecore_evas/engines/sdl/ecore_evas_sdl.c
src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_common.c
src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_egl.c
src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_shm.c
src/modules/ecore_evas/engines/win32/ecore_evas_win32.c
src/modules/ecore_evas/engines/x/ecore_evas_x.c
src/modules/ecore_evas/vnc_server/ecore_evas_vnc_server.c
src/modules/elementary/access_output/mod.c
src/modules/elementary/prefs/prefs_iface.c
src/modules/elementary/test_entry/mod.c
src/modules/elementary/test_map/mod.c
src/modules/elementary/web/none/elm_web_none.c
src/modules/evas/engines/gl_common/evas_gl_common.h
src/modules/evas/engines/gl_common/evas_gl_context.c
src/modules/evas/engines/gl_common/evas_gl_core.c
src/modules/evas/engines/gl_common/evas_gl_core.h
src/modules/evas/engines/gl_common/evas_gl_image.c
src/modules/evas/engines/gl_common/evas_gl_preload.c
src/modules/evas/engines/gl_common/evas_gl_shader.c
src/modules/evas/engines/gl_generic/evas_ector_gl.h
src/modules/evas/engines/gl_generic/meson.build
src/modules/evas/engines/software_generic/evas_ector_software.h
src/modules/evas/engines/software_generic/evas_native_common.h
src/modules/evas/engines/software_generic/evas_native_tbm.c
src/modules/evas/image_loaders/eet/evas_image_load_eet.c
src/modules/evas/image_savers/eet/evas_image_save_eet.c

Differentiate building a module and building a EFL library

[modules] Rename EAPI symbol to EMODAPI symbol

---

src/lib/evil/evil_fcntl.h

My bad, that little PR #194 was merged with a very mad typo.

typo in _MSC_VER

---

header_checks/meson.build
src/lib/eina/meson.build
src/lib/emile/meson.build
src/lib/evil/meson.build
src/tests/eina/meson.build
src/tests/eolian/meson.build
src/tests/evil/meson.build

And also remove unnecessary pcre dependency in eina

build: Undo _dep suffix on dependencies.

---

src/lib/evas/Evas_Internal.h

[evas] Bug: Remove remainging EAPI

---

src/bin/elementary/perf.c
src/bin/exactness/player.c
src/bin/exactness/recorder.c

EAPI was being used at bin but as it isn't declared anymore its
generating some errors.

[bin] Remove EAPI uses

---

src/static_libs/buildsystem/meson.build

Removing redefinition of PACKAGE_SRC_DIR for linux

---

.travis.yml

[CI] Enable Wayland and `options-enabled` builds at Travis-CI

---

src/lib/ecore_con/Ecore_Con.h
src/lib/ecore_con/Efl_Net.h
src/lib/ecore_con/ecore_con.c
src/lib/ecore_con/ecore_con_local.c
src/lib/ecore_con/ecore_con_proxy_helper.c
src/lib/ecore_con/ecore_con_socks.c
src/lib/ecore_con/ecore_con_url.c
src/lib/ecore_con/ecore_con_url_curl.c
src/lib/ecore_con/ecore_con_url_curl.h
src/lib/ecore_file/ecore_file.c

Based on [946db](https://github.com/expertisesolutions/efl/commit/946db)

ecore_con: Add guards to some includes

---

src/lib/ecore_win32/ecore_win32_dnd.c

Original: https://github.com/expertisesolutions/efl/commit/4116cd0904ae6b7556ce3e2674fe3eee34187219

Addming a missing ole2 header

---

src/lib/evil/evil_stdio.c
src/lib/evil/evil_stdio.h
src/lib/evil/evil_vasprintf.h

Based on [e9e7f95](https://github.com/expertisesolutions/efl/commit/e9e7f9512cea1074fee5a06edcea908044bd7b82)

evil: Define asprintf

---

src/lib/ecore_evas/ecore_evas_ews.c
src/lib/ecore_evas/meson.build
src/lib/ecore_imf/ecore_imf_module.c
src/lib/evas/canvas/evas_image_private.h
src/modules/ecore_evas/engines/win32/ecore_evas_win32.c

Based on https://github.com/expertisesolutions/efl/commit/e57193b680f3383dda685c6fa122577874ad7292

Ecore-evas api related fixes

---

build.bat
configure.bat
ensure-vcvars64.bat

build: Check VS edition instead of assuming Professional

---

header_checks/meson.build
src/lib/evil/evil_private.h
src/lib/evil/evil_unistd.c
src/lib/evil/evil_unistd.h

Define sleep function and HAVE_SLEEP macro for windows builds if sleep is not already
defined.

evil: Define sleep

---

header_checks/meson.build
subprojects/libjpeg.wrap

Needs a meson with https://github.com/mesonbuild/meson/pull/7381.

build: Fallback libjpeg to wrap

---

src/lib/eina/eina_thread_win32.c

Based on: ae462147fd6beff0ad3c0a96280e5e31ba3d1f0a

eina: Check if thread is null before accessing its values on eina_thread_cancel

---

meson.build

Evas will be building as soon as we fix jpeg and lua.
This PR depens on:
- #291 (merged)
- #292 (merged)
For reviewers, please take a look directly here: 7ca3e0a38d1b568a11a24b67b3bf9fd5c7dd0058.

[Deps] [Redone] Evas

---

configure.bat
meson.build

Based on:
- f95e9d60291af529a3fcb9ca8a0d541c91b1473d
- 2f3c8295db3e1fa9c62462dbeb6057085e19f87e
Depends on #354

Enable compilation of examples

---

src/examples/evas/evas-text.c
src/lib/evas/canvas/evas_font_dir.c

originally:  
- ad327702366ba2939d952f6d7718d2d1c6b91d8b
- 681218b9fe3824bf0d817531b7abfe7a1277f4bd

[Evas] Fix fonts for win32

---

meson.build

Embryo can be built but there is not test or examples to try.

[Deps] Enable embryo

---

src/examples/edje/meson.build

Original: 8c535592114f74173a66d00adaabecf10f73c047

edje: Only compile svg edje if evas svg loader is enabled

---

src/lib/ecore_con/ecore_con_url_curl.c

Original: c2c869789d038c87657974395b497c3bea67b971

win32: Do not fail if we can't find libcurl

---

configure.bat
meson.build
meson_options.txt
src/bin/elementary/meson.build
src/bin/elementary/test.c
src/bin/elementary/test_fileselector.c
src/bin/elementary/test_photo.c
src/edje_external/elementary/meson.build
src/edje_external/elementary/modules.inc
src/examples/elementary/filemvc.c
src/examples/elementary/fileselector_example.c
src/examples/elementary/meson.build
src/lib/elementary/Elementary.h
src/lib/elementary/elm_icon.c
src/lib/elementary/elm_widget_icon.h
src/lib/elementary/meson.build
src/tests/elementary/elm_suite.c
src/tests/elementary/meson.build

Original: 3626e00dd1329d56cacab614f380f0facb162a8b

win32: Make ethumb optional

---

src/examples/eina/eina_file_01.c

Use `eina_environment_home_get` to get home dir instead of using
`/home/`

eina: Resolve eina_file01.exe
